const CONFIG = {};
CONFIG.canvas = document.getElementById('game-canvas');
CONFIG.context = CONFIG.canvas.getContext('2d');
CONFIG.canvasBounding = CONFIG.canvas.getBoundingClientRect();
CONFIG.WIDTH = CONFIG.canvas.width;
CONFIG.HEIGHT = CONFIG.canvas.height;
CONFIG.CANVAS_X = CONFIG.canvasBounding.left;
CONFIG.CANVAS_Y = CONFIG.canvasBounding.top;
CONFIG.PIECE_RADIUS = CONFIG.WIDTH / (25 * 2);
CONFIG.PIECE_DIAMETER = 2 * CONFIG.PIECE_RADIUS;
CONFIG.BOARD_BORDER_WIDTH = CONFIG.WIDTH * 2 / 100;
CONFIG.UPPER_BASE =  CONFIG.HEIGHT * 2 / 100;
CONFIG.LOWER_BASE = CONFIG.HEIGHT - CONFIG.UPPER_BASE;
CONFIG.COLUMN_MAX_PIECE_HEIGHT = 7;
CONFIG.PIx2 = 2 * Math.PI;
CONFIG.BLACK = 'black';
CONFIG.WHITE = 'yellow';
CONFIG.HIGHLIGHT = '#A020F030';
CONFIG.COLUMN_WIDTH = CONFIG.WIDTH / 16;
CONFIG.EDGE_WIDTH = CONFIG.COLUMN_WIDTH;
CONFIG.BOARD_SPLIT_WIDTH = 2 * CONFIG.COLUMN_WIDTH;
CONFIG.MIDDLE_WIDTH = 6 * CONFIG.COLUMN_WIDTH;
CONFIG.PLAYING_CLOCKWISE_TAGS = [
    'CW', ...'ABCDEF', 'SB', ...'GHIJKL',
    'CB', ...'MNOPQR', 'SW', ...'STUVWX'
];
CONFIG.PLAYING_COUNTER_CLOCKWISE_TAGS = [
    'CB', ...'MNOPQR', 'SW', ...'STUVWX',
    'CW', ...'ABCDEF', 'SB', ...'GHIJKL'
];

CONFIG.context.strokeStyle='purple';

export default CONFIG;