/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.afloarea.jackgammon.juliette;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final Logger LOG = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        final var board = new DefaultGameBoard();
        board.init();
        System.out.println(board);
    }
}
